#!/bin/bash
path=dist

js=(semantic school notice wellcome info img header footer home index)
#js=(header index)
minjs=(index)

#color
red=`tput setaf 1`
reset=`tput sgr0`

if [ $# = 1 ]; then
#start
  if [ $1 = init ]; then
    cd ${path}
    npm install -i
    cp bower_components/semantic/dist/semantic.min.css ../css/semantic.min.css
    cp bower_components/semantic/dist/themes ../css/themes -R
    cp bower_components/semantic/dist/components ../css/components -R

#transform js from jsx
  elif [ $1 = jsx ]; then
    echo
    echo "jsx"
    ${path}/node_modules/.bin/jsx src/ dist/
    echo "done"
    echo

#browerify js file
  elif [ $1 = bro ]; then
    echo
    echo "browserify"
    cd ${path}
    for item in ${js[*]}; do
      node_modules/.bin/browserify ${item}.js > ../js/${item}.temp.js
      echo "${red}${item}.js is complate.${reset}"
    done
    echo "done"
    echo 

#minify js
  elif [ $1 = min ]; then
    echo
    echo "minifier"
    cd js
    for item in ${minjs[*]}; do
      echo "${red}${item}.js${reset}"
      ../${path}/node_modules/.bin/minify ${item}.temp.js --output ${item}.min.js
    done
    echo "done"
    echo
  fi

#use npm
elif [ $1 = npm ]; then
  cd ${path}
  $@

#use bower
elif [ $1 = bower ]; then
  cd ${path}
  node_modules/.bin/$@
fi
