#!/bin/sh
if [ "$#" = 1 ]; then
  if [ "$1" = "init" ]; then
    cd lib
    npm install -i
  elif  [ "$1" = "jsx" ]; then
    lib/node_modules/react-tools/bin/jsx src js/
  fi
elif [ "$1" = "npm" ]; then
  cd lib
  $@
elif [ "$1" = "bower" ]; then
  cd lib
  node_modules/bower/bin/$@
fi
